name: CI

on:
  pull_request:
    branches: [ "main", "DEV" ]
  push:
    branches: [ "main", "DEV", ]

jobs:
  test:
    name: Lint & Test (Python ${{ matrix.python-version }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [ "3.10", "3.11", "3.12" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest flake8 pytest-cov

      - name: Flake8 (fail only fail on critical issus)
        run: |
          flake8 .

      #- name: Pytest (with coverage)
      #  run: |
      #    pytest -q -m "not skip_in_ci" --cov=. --cov-report=xml --cov-report=term-missing
      
      #- name: Upload coverage XML
      #  if: always()
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: coverage-xml-${{ runner.os }}-py${{ matrix.python-version }}-${{ github.job }}-run${{ github.run_attempt }}
      #    path: coverage.xml
      #    if-no-files-found: warn
      #    compression-level: 6
      #    overwrite: false
